using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Model.EDI.X12.v2.Base;

namespace Model.EDI.X12.v2
{
    public class IeaCollection : SegmentCollection { public IeaCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(IEA), owningLoopEntity, SegmentDef) { } public IEA this[int index] { get { return Segments[index] as IEA; } set { Segments[index] = value; } } }
    public class GsCollection : SegmentCollection { public GsCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(GS), owningLoopEntity, SegmentDef) { } public GS this[int index] { get { return Segments[index] as GS; } set { Segments[index] = value; } } }
    public class IsaCollection : SegmentCollection { public IsaCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(ISA), owningLoopEntity, SegmentDef) { } public ISA this[int index] { get { return Segments[index] as ISA; } set { Segments[index] = value; } } }
    public class GeCollection : SegmentCollection { public GeCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(GE), owningLoopEntity, SegmentDef) { } public GE this[int index] { get { return Segments[index] as GE; } set { Segments[index] = value; } } }
    public class StCollection : SegmentCollection { public StCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(ST), owningLoopEntity, SegmentDef) { } public ST this[int index] { get { return Segments[index] as ST; } set { Segments[index] = value; } } }
    public class BhtCollection : SegmentCollection { public BhtCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(BHT), owningLoopEntity, SegmentDef) { } public BHT this[int index] { get { return Segments[index] as BHT; } set { Segments[index] = value; } } }
    public class SeCollection : SegmentCollection { public SeCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(SE), owningLoopEntity, SegmentDef) { } public SE this[int index] { get { return Segments[index] as SE; } set { Segments[index] = value; } } }
    public class HlCollection : SegmentCollection { public HlCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(HL), owningLoopEntity, SegmentDef) { } public HL this[int index] { get { return Segments[index] as HL; } set { Segments[index] = value; } } }
    public class Nm1Collection : SegmentCollection { public Nm1Collection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(NM1), owningLoopEntity, SegmentDef) { } public NM1 this[int index] { get { return Segments[index] as NM1; } set { Segments[index] = value; } } }
    public class DmgCollection : SegmentCollection { public DmgCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(DMG), owningLoopEntity, SegmentDef) { } public DMG this[int index] { get { return Segments[index] as DMG; } set { Segments[index] = value; } } }
    public class TrnCollection : SegmentCollection { public TrnCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(TRN), owningLoopEntity, SegmentDef) { } public TRN this[int index] { get { return Segments[index] as TRN; } set { Segments[index] = value; } } }
    public class RefCollection : SegmentCollection { public RefCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(REF), owningLoopEntity, SegmentDef) { } public REF this[int index] { get { return Segments[index] as REF; } set { Segments[index] = value; } } }
    public class AmtCollection : SegmentCollection { public AmtCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(AMT), owningLoopEntity, SegmentDef) { } public AMT this[int index] { get { return Segments[index] as AMT; } set { Segments[index] = value; } } }
    public class DtpCollection : SegmentCollection { public DtpCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(DTP), owningLoopEntity, SegmentDef) { } public DTP this[int index] { get { return Segments[index] as DTP; } set { Segments[index] = value; } } }
    public class SvcCollection : SegmentCollection { public SvcCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(SVC), owningLoopEntity, SegmentDef) { } public SVC this[int index] { get { return Segments[index] as SVC; } set { Segments[index] = value; } } }
    public class StcCollection : SegmentCollection { public StcCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(STC), owningLoopEntity, SegmentDef) { } public STC this[int index] { get { return Segments[index] as STC; } set { Segments[index] = value; } } }
    public class PerCollection : SegmentCollection { public PerCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(PER), owningLoopEntity, SegmentDef) { } public PER this[int index] { get { return Segments[index] as PER; } set { Segments[index] = value; } } }
    public class SbrCollection : SegmentCollection { public SbrCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(SBR), owningLoopEntity, SegmentDef) { } public SBR this[int index] { get { return Segments[index] as SBR; } set { Segments[index] = value; } } }
    public class PatCollection : SegmentCollection { public PatCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(PAT), owningLoopEntity, SegmentDef) { } public PAT this[int index] { get { return Segments[index] as PAT; } set { Segments[index] = value; } } }
    public class N3Collection : SegmentCollection { public N3Collection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(N3), owningLoopEntity, SegmentDef) { } public N3 this[int index] { get { return Segments[index] as N3; } set { Segments[index] = value; } } }
    public class N4Collection : SegmentCollection { public N4Collection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(N4), owningLoopEntity, SegmentDef) { } public N4 this[int index] { get { return Segments[index] as N4; } set { Segments[index] = value; } } }
    public class ClmCollection : SegmentCollection { public ClmCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(CLM), owningLoopEntity, SegmentDef) { } public CLM this[int index] { get { return Segments[index] as CLM; } set { Segments[index] = value; } } }
    public class PrvCollection : SegmentCollection { public PrvCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(PRV), owningLoopEntity, SegmentDef) { } public PRV this[int index] { get { return Segments[index] as PRV; } set { Segments[index] = value; } } }
    public class CurCollection : SegmentCollection { public CurCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(CUR), owningLoopEntity, SegmentDef) { } public CUR this[int index] { get { return Segments[index] as CUR; } set { Segments[index] = value; } } }
    public class PwkCollection : SegmentCollection { public PwkCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(PWK), owningLoopEntity, SegmentDef) { } public PWK this[int index] { get { return Segments[index] as PWK; } set { Segments[index] = value; } } }
    public class Cn1Collection : SegmentCollection { public Cn1Collection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(CN1), owningLoopEntity, SegmentDef) { } public CN1 this[int index] { get { return Segments[index] as CN1; } set { Segments[index] = value; } } }
    public class K3Collection : SegmentCollection { public K3Collection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(K3), owningLoopEntity, SegmentDef) { } public K3 this[int index] { get { return Segments[index] as K3; } set { Segments[index] = value; } } }
    public class NteCollection : SegmentCollection { public NteCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(NTE), owningLoopEntity, SegmentDef) { } public NTE this[int index] { get { return Segments[index] as NTE; } set { Segments[index] = value; } } }
    public class Cr1Collection : SegmentCollection { public Cr1Collection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(CR1), owningLoopEntity, SegmentDef) { } public CR1 this[int index] { get { return Segments[index] as CR1; } set { Segments[index] = value; } } }
    public class Cr2Collection : SegmentCollection { public Cr2Collection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(CR2), owningLoopEntity, SegmentDef) { } public CR2 this[int index] { get { return Segments[index] as CR2; } set { Segments[index] = value; } } }
    public class CrcCollection : SegmentCollection { public CrcCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(CRC), owningLoopEntity, SegmentDef) { } public CRC this[int index] { get { return Segments[index] as CRC; } set { Segments[index] = value; } } }
    public class HiCollection : SegmentCollection { public HiCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(HI), owningLoopEntity, SegmentDef) { } public HI this[int index] { get { return Segments[index] as HI; } set { Segments[index] = value; } } }
    public class HcpCollection : SegmentCollection { public HcpCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(HCP), owningLoopEntity, SegmentDef) { } public HCP this[int index] { get { return Segments[index] as HCP; } set { Segments[index] = value; } } }
    public class CasCollection : SegmentCollection { public CasCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(CAS), owningLoopEntity, SegmentDef) { } public CAS this[int index] { get { return Segments[index] as CAS; } set { Segments[index] = value; } } }
    public class OiCollection : SegmentCollection { public OiCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(OI), owningLoopEntity, SegmentDef) { } public OI this[int index] { get { return Segments[index] as OI; } set { Segments[index] = value; } } }
    public class MoaCollection : SegmentCollection { public MoaCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(MOA), owningLoopEntity, SegmentDef) { } public MOA this[int index] { get { return Segments[index] as MOA; } set { Segments[index] = value; } } }
    public class LxCollection : SegmentCollection { public LxCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(LX), owningLoopEntity, SegmentDef) { } public LX this[int index] { get { return Segments[index] as LX; } set { Segments[index] = value; } } }
    public class Sv1Collection : SegmentCollection { public Sv1Collection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(SV1), owningLoopEntity, SegmentDef) { } public SV1 this[int index] { get { return Segments[index] as SV1; } set { Segments[index] = value; } } }
    public class Sv5Collection : SegmentCollection { public Sv5Collection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(SV5), owningLoopEntity, SegmentDef) { } public SV5 this[int index] { get { return Segments[index] as SV5; } set { Segments[index] = value; } } }
    public class Cr3Collection : SegmentCollection { public Cr3Collection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(CR3), owningLoopEntity, SegmentDef) { } public CR3 this[int index] { get { return Segments[index] as CR3; } set { Segments[index] = value; } } }
    public class QtyCollection : SegmentCollection { public QtyCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(QTY), owningLoopEntity, SegmentDef) { } public QTY this[int index] { get { return Segments[index] as QTY; } set { Segments[index] = value; } } }
    public class MeaCollection : SegmentCollection { public MeaCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(MEA), owningLoopEntity, SegmentDef) { } public MEA this[int index] { get { return Segments[index] as MEA; } set { Segments[index] = value; } } }
    public class Ps1Collection : SegmentCollection { public Ps1Collection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(PS1), owningLoopEntity, SegmentDef) { } public PS1 this[int index] { get { return Segments[index] as PS1; } set { Segments[index] = value; } } }
    public class LinCollection : SegmentCollection { public LinCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(LIN), owningLoopEntity, SegmentDef) { } public LIN this[int index] { get { return Segments[index] as LIN; } set { Segments[index] = value; } } }
    public class CtpCollection : SegmentCollection { public CtpCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(CTP), owningLoopEntity, SegmentDef) { } public CTP this[int index] { get { return Segments[index] as CTP; } set { Segments[index] = value; } } }
    public class SvdCollection : SegmentCollection { public SvdCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(SVD), owningLoopEntity, SegmentDef) { } public SVD this[int index] { get { return Segments[index] as SVD; } set { Segments[index] = value; } } }
    public class LqCollection : SegmentCollection { public LqCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(LQ), owningLoopEntity, SegmentDef) { } public LQ this[int index] { get { return Segments[index] as LQ; } set { Segments[index] = value; } } }
    public class FrmCollection : SegmentCollection { public FrmCollection(LoopEntity owningLoopEntity, BaseStdSegment SegmentDef) : base(typeof(FRM), owningLoopEntity, SegmentDef) { } public FRM this[int index] { get { return Segments[index] as FRM; } set { Segments[index] = value; } } }

}
