public void SetUpWholeDefinition(){
DocumentDefinition = new X12DocDefinition(); 
//MainLoops
var Loop2000ADefinition = new LoopDefinition(999); 
Loop2000ADefinition.LoopName = "2000A"; 
Loop2000ADefinition.LoopDescription = "INFORMATIONSOURCELEVEL"; 
DocumentDefinition.loops.Add(Loop2000ADefinition); 
var Loop2100ADefinition = new LoopDefinition(1); 
Loop2100ADefinition.LoopName = "2100A"; 
Loop2100ADefinition.LoopDescription = "PAYERNAME"; 
DocumentDefinition.loops.Add(Loop2100ADefinition); 
var Loop2000BDefinition = new LoopDefinition(999); 
Loop2000BDefinition.LoopName = "2000B"; 
Loop2000BDefinition.LoopDescription = "INFORMATIONRECEIVERLEVEL"; 
DocumentDefinition.loops.Add(Loop2000BDefinition); 
var Loop2100BDefinition = new LoopDefinition(1); 
Loop2100BDefinition.LoopName = "2100B"; 
Loop2100BDefinition.LoopDescription = "INFORMATIONRECEIVERNAME"; 
DocumentDefinition.loops.Add(Loop2100BDefinition); 
var Loop2200BDefinition = new LoopDefinition(1); 
Loop2200BDefinition.LoopName = "2200B"; 
Loop2200BDefinition.LoopDescription = "INFORMATIONRECEIVERTRACEIDENTIFIER"; 
DocumentDefinition.loops.Add(Loop2200BDefinition); 

//
//subLoops
var Loop2000CDefinition = new LoopDefinition(999); 
Loop2000CDefinition.LoopName = "2000C"; 
Loop2000CDefinition.LoopDescription = "SERVICEPROVIDERLEVEL"; 
Loop2200BDefinition.SubLoops.Add(Loop2000CDefinition); 
var Loop2100CDefinition = new LoopDefinition(999); 
Loop2100CDefinition.LoopName = "2100C"; 
Loop2100CDefinition.LoopDescription = "PROVIDERNAME"; 
Loop2200BDefinition.SubLoops.Add(Loop2100CDefinition); 
var Loop2200CDefinition = new LoopDefinition(1); 
Loop2200CDefinition.LoopName = "2200C"; 
Loop2200CDefinition.LoopDescription = "PROVIDEROFSERVICETRACEIDENTIFIER"; 
Loop2200BDefinition.SubLoops.Add(Loop2200CDefinition); 
var Loop2000DDefinition = new LoopDefinition(999); 
Loop2000DDefinition.LoopName = "2000D"; 
Loop2000DDefinition.LoopDescription = "SUBSCRIBERLEVEL"; 
Loop2200CDefinition.SubLoops.Add(Loop2000DDefinition); 
var Loop2100DDefinition = new LoopDefinition(1); 
Loop2100DDefinition.LoopName = "2100D"; 
Loop2100DDefinition.LoopDescription = "SUBSCRIBERNAME"; 
Loop2200CDefinition.SubLoops.Add(Loop2100DDefinition); 
var Loop2200DDefinition = new LoopDefinition(999); 
Loop2200DDefinition.LoopName = "2200D"; 
Loop2200DDefinition.LoopDescription = "CLAIMSTATUSTRACKINGNUMBER"; 
Loop2100DDefinition.SubLoops.Add(Loop2200DDefinition); 
var Loop2220DDefinition = new LoopDefinition(999); 
Loop2220DDefinition.LoopName = "2220D"; 
Loop2220DDefinition.LoopDescription = "SERVICELINEINFORMATION"; 
Loop2200DDefinition.SubLoops.Add(Loop2220DDefinition); 
var Loop2000EDefinition = new LoopDefinition(999); 
Loop2000EDefinition.LoopName = "2000E"; 
Loop2000EDefinition.LoopDescription = "DEPENDENTLEVEL"; 
Loop2200DDefinition.SubLoops.Add(Loop2000EDefinition); 
var Loop2100EDefinition = new LoopDefinition(1); 
Loop2100EDefinition.LoopName = "2100E"; 
Loop2100EDefinition.LoopDescription = "DEPENDENTNAME"; 
Loop2200DDefinition.SubLoops.Add(Loop2100EDefinition); 
var Loop2200EDefinition = new LoopDefinition(999); 
Loop2200EDefinition.LoopName = "2200E"; 
Loop2200EDefinition.LoopDescription = "CLAIMSTATUSTRACKINGNUMBER"; 
Loop2200DDefinition.SubLoops.Add(Loop2200EDefinition); 
var Loop2220EDefinition = new LoopDefinition(999); 
Loop2220EDefinition.LoopName = "2220E"; 
Loop2220EDefinition.LoopDescription = "SERVICELINEINFORMATION"; 
Loop2200EDefinition.SubLoops.Add(Loop2220EDefinition); 

//
//segments
var HL_InformationSourceLevel_Loop2000ADefinition = new SegmentDefinition(SegmentUsageType.Required,1,typeof(HL));
Loop2000ADefinition.LoopSegments.Add(HL_InformationSourceLevel_Loop2000ADefinition); 
var NM1_PayerName_Loop2100ADefinition = new SegmentDefinition(SegmentUsageType.Required,1,typeof(NM1));
Loop2100ADefinition.LoopSegments.Add(NM1_PayerName_Loop2100ADefinition); 
var PER_PayerContactInformation_Loop2100ADefinition = new SegmentDefinition(SegmentUsageType.Optional,1,typeof(PER));
Loop2100ADefinition.LoopSegments.Add(PER_PayerContactInformation_Loop2100ADefinition); 
var HL_InformationReceiverLevel_Loop2000BDefinition = new SegmentDefinition(SegmentUsageType.Required,1,typeof(HL));
Loop2000BDefinition.LoopSegments.Add(HL_InformationReceiverLevel_Loop2000BDefinition); 
var NM1_InformationReceiverName_Loop2100BDefinition = new SegmentDefinition(SegmentUsageType.Required,1,typeof(NM1));
Loop2100BDefinition.LoopSegments.Add(NM1_InformationReceiverName_Loop2100BDefinition); 
var TRN_InformationReceiverTraceIdentifier_Loop2200BDefinition = new SegmentDefinition(SegmentUsageType.Optional,1,typeof(TRN));
Loop2200BDefinition.LoopSegments.Add(TRN_InformationReceiverTraceIdentifier_Loop2200BDefinition); 
var STC_InformationReceiverStatusInformation_Loop2200BDefinition = new SegmentDefinition(SegmentUsageType.Required,0,typeof(STC));
Loop2200BDefinition.LoopSegments.Add(STC_InformationReceiverStatusInformation_Loop2200BDefinition); 
var HL_ServiceProviderLevel_Loop2000CDefinition = new SegmentDefinition(SegmentUsageType.Optional,1,typeof(HL));
Loop2000CDefinition.LoopSegments.Add(HL_ServiceProviderLevel_Loop2000CDefinition); 
var NM1_ProviderName_Loop2100CDefinition = new SegmentDefinition(SegmentUsageType.Required,1,typeof(NM1));
Loop2100CDefinition.LoopSegments.Add(NM1_ProviderName_Loop2100CDefinition); 
var TRN_ProviderofServiceTraceIdentifier_Loop2200CDefinition = new SegmentDefinition(SegmentUsageType.Optional,1,typeof(TRN));
Loop2200CDefinition.LoopSegments.Add(TRN_ProviderofServiceTraceIdentifier_Loop2200CDefinition); 
var STC_ProviderStatusInformation_Loop2200CDefinition = new SegmentDefinition(SegmentUsageType.Required,0,typeof(STC));
Loop2200CDefinition.LoopSegments.Add(STC_ProviderStatusInformation_Loop2200CDefinition); 
var HL_SubscriberLevel_Loop2000DDefinition = new SegmentDefinition(SegmentUsageType.Optional,1,typeof(HL));
Loop2000DDefinition.LoopSegments.Add(HL_SubscriberLevel_Loop2000DDefinition); 
var NM1_SubscriberName_Loop2100DDefinition = new SegmentDefinition(SegmentUsageType.Required,1,typeof(NM1));
Loop2100DDefinition.LoopSegments.Add(NM1_SubscriberName_Loop2100DDefinition); 
var TRN_ClaimStatusTrackingNumber_Loop2200DDefinition = new SegmentDefinition(SegmentUsageType.Optional,1,typeof(TRN));
Loop2200DDefinition.LoopSegments.Add(TRN_ClaimStatusTrackingNumber_Loop2200DDefinition); 
var STC_ClaimLevelStatusInformation_Loop2200DDefinition = new SegmentDefinition(SegmentUsageType.Required,0,typeof(STC));
Loop2200DDefinition.LoopSegments.Add(STC_ClaimLevelStatusInformation_Loop2200DDefinition); 
var REF_PayerClaimControlNumber_Loop2200DDefinition = new SegmentDefinition(SegmentUsageType.Optional,1,typeof(REF));
Loop2200DDefinition.LoopSegments.Add(REF_PayerClaimControlNumber_Loop2200DDefinition); 
var REF_InstitutionalBillTypeIdentification_Loop2200DDefinition = new SegmentDefinition(SegmentUsageType.Optional,1,typeof(REF));
Loop2200DDefinition.LoopSegments.Add(REF_InstitutionalBillTypeIdentification_Loop2200DDefinition); 
var REF_PatientControlNumber_Loop2200DDefinition = new SegmentDefinition(SegmentUsageType.Optional,1,typeof(REF));
Loop2200DDefinition.LoopSegments.Add(REF_PatientControlNumber_Loop2200DDefinition); 
var REF_PharmacyPrescriptionNumber_Loop2200DDefinition = new SegmentDefinition(SegmentUsageType.Optional,1,typeof(REF));
Loop2200DDefinition.LoopSegments.Add(REF_PharmacyPrescriptionNumber_Loop2200DDefinition); 
var REF_VoucherIdentifier_Loop2200DDefinition = new SegmentDefinition(SegmentUsageType.Optional,1,typeof(REF));
Loop2200DDefinition.LoopSegments.Add(REF_VoucherIdentifier_Loop2200DDefinition); 
var REF_ClaimIdentificationNumberForClearinghousesand_Loop2200DDefinition = new SegmentDefinition(SegmentUsageType.Optional,0,typeof(REF));
Loop2200DDefinition.LoopSegments.Add(REF_ClaimIdentificationNumberForClearinghousesand_Loop2200DDefinition); 
var DTP_ClaimServiceDate_Loop2200DDefinition = new SegmentDefinition(SegmentUsageType.Optional,1,typeof(DTP));
Loop2200DDefinition.LoopSegments.Add(DTP_ClaimServiceDate_Loop2200DDefinition); 
var SVC_ServiceLineInformation_Loop2220DDefinition = new SegmentDefinition(SegmentUsageType.Optional,1,typeof(SVC));
Loop2220DDefinition.LoopSegments.Add(SVC_ServiceLineInformation_Loop2220DDefinition); 
var STC_ServiceLineStatusInformation_Loop2220DDefinition = new SegmentDefinition(SegmentUsageType.Required,0,typeof(STC));
Loop2220DDefinition.LoopSegments.Add(STC_ServiceLineStatusInformation_Loop2220DDefinition); 
var REF_ServiceLineItemIdentification_Loop2220DDefinition = new SegmentDefinition(SegmentUsageType.Optional,1,typeof(REF));
Loop2220DDefinition.LoopSegments.Add(REF_ServiceLineItemIdentification_Loop2220DDefinition); 
var DTP_ServiceLineDate_Loop2220DDefinition = new SegmentDefinition(SegmentUsageType.Required,1,typeof(DTP));
Loop2220DDefinition.LoopSegments.Add(DTP_ServiceLineDate_Loop2220DDefinition); 
var HL_DependentLevel_Loop2000EDefinition = new SegmentDefinition(SegmentUsageType.Optional,1,typeof(HL));
Loop2000EDefinition.LoopSegments.Add(HL_DependentLevel_Loop2000EDefinition); 
var NM1_DependentName_Loop2100EDefinition = new SegmentDefinition(SegmentUsageType.Required,1,typeof(NM1));
Loop2100EDefinition.LoopSegments.Add(NM1_DependentName_Loop2100EDefinition); 
var TRN_ClaimStatusTrackingNumber_Loop2200EDefinition = new SegmentDefinition(SegmentUsageType.Required,1,typeof(TRN));
Loop2200EDefinition.LoopSegments.Add(TRN_ClaimStatusTrackingNumber_Loop2200EDefinition); 
var STC_ClaimLevelStatusInformation_Loop2200EDefinition = new SegmentDefinition(SegmentUsageType.Required,0,typeof(STC));
Loop2200EDefinition.LoopSegments.Add(STC_ClaimLevelStatusInformation_Loop2200EDefinition); 
var REF_PayerClaimControlNumber_Loop2200EDefinition = new SegmentDefinition(SegmentUsageType.Optional,1,typeof(REF));
Loop2200EDefinition.LoopSegments.Add(REF_PayerClaimControlNumber_Loop2200EDefinition); 
var REF_InstitutionalBillTypeIdentification_Loop2200EDefinition = new SegmentDefinition(SegmentUsageType.Optional,1,typeof(REF));
Loop2200EDefinition.LoopSegments.Add(REF_InstitutionalBillTypeIdentification_Loop2200EDefinition); 
var REF_PatientControlNumber_Loop2200EDefinition = new SegmentDefinition(SegmentUsageType.Optional,1,typeof(REF));
Loop2200EDefinition.LoopSegments.Add(REF_PatientControlNumber_Loop2200EDefinition); 
var REF_PharmacyPrescriptionNumber_Loop2200EDefinition = new SegmentDefinition(SegmentUsageType.Optional,1,typeof(REF));
Loop2200EDefinition.LoopSegments.Add(REF_PharmacyPrescriptionNumber_Loop2200EDefinition); 
var REF_VoucherIdentifier_Loop2200EDefinition = new SegmentDefinition(SegmentUsageType.Optional,1,typeof(REF));
Loop2200EDefinition.LoopSegments.Add(REF_VoucherIdentifier_Loop2200EDefinition); 
var REF_ClaimIdentificationNumberForClearinghousesand_Loop2200EDefinition = new SegmentDefinition(SegmentUsageType.Optional,0,typeof(REF));
Loop2200EDefinition.LoopSegments.Add(REF_ClaimIdentificationNumberForClearinghousesand_Loop2200EDefinition); 
var DTP_ClaimServiceDate_Loop2200EDefinition = new SegmentDefinition(SegmentUsageType.Optional,1,typeof(DTP));
Loop2200EDefinition.LoopSegments.Add(DTP_ClaimServiceDate_Loop2200EDefinition); 
var SVC_ServiceLineInformation_Loop2220EDefinition = new SegmentDefinition(SegmentUsageType.Optional,1,typeof(SVC));
Loop2220EDefinition.LoopSegments.Add(SVC_ServiceLineInformation_Loop2220EDefinition); 
var STC_ServiceLineStatusInformation_Loop2220EDefinition = new SegmentDefinition(SegmentUsageType.Required,0,typeof(STC));
Loop2220EDefinition.LoopSegments.Add(STC_ServiceLineStatusInformation_Loop2220EDefinition); 
var REF_ServiceLineItemIdentification_Loop2220EDefinition = new SegmentDefinition(SegmentUsageType.Optional,1,typeof(REF));
Loop2220EDefinition.LoopSegments.Add(REF_ServiceLineItemIdentification_Loop2220EDefinition); 
var DTP_ServiceLineDate_Loop2220EDefinition = new SegmentDefinition(SegmentUsageType.Required,1,typeof(DTP));
Loop2220EDefinition.LoopSegments.Add(DTP_ServiceLineDate_Loop2220EDefinition); 
var SE_TransactionSetTrailer_Loop2220EDefinition = new SegmentDefinition(SegmentUsageType.Required,1,typeof(SE));
Loop2220EDefinition.LoopSegments.Add(SE_TransactionSetTrailer_Loop2220EDefinition); 

//
}
